version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skillbridge
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/skillbridge?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis

  frontend:
    build: ./skillbridge-pro-86
    command: sh -c "npm install && npm run dev -- --host"
    working_dir: /usr/src/app
    volumes:
      - ./skillbridge-pro-86:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api/v1
    depends_on:
      - backend

volumes:
  db-data:
  redis-data:
